---
name: Email-MIME-XMTP
version: 0.35
author:
  - Alberto Reggiori <alberto@asemantics.com>
abstract: Add XMTP support to Email::MIME
license: bsd
requires:
  Email::MIME: 1.82
  Email::MIME::Encodings: 1.3
  Email::Simple: 1.92
  Test::More: 0.47
  XML::Parser: 2.20
provides:
  Email::MIME:
    file: lib/Email/MIME/XMTP.pm
    version: 0.35
  Email::MIME::XMTP:
    file: lib/Email/MIME/XMTP.pm
    version: 0.35
generated_by: Module::Build version 0.2608
